# Generated by Django 4.1.1 on 2022-09-06 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_banners'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banners',
            new_name='Banner',
        ),
    ]
