# Generated by Django 4.1.1 on 2022-09-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_banners_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='Link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
