# Generated by Django 4.1.1 on 2022-09-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_brand_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
