# Generated by Django 4.1.1 on 2022-09-09 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_product_name_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='featured_image',
            new_name='image',
        ),
    ]
